name = "ia-drive"
main = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "THUMBS"
bucket_name = "ia-thumbs"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "ia-uploads"

[[kv_namespaces]]
binding = "SHARES"
id = "your_kv_id_here"

[vars]
IA_BUCKET = "junk-manage-caution"
